// Code generated by github.com/izumin5210/grapi. DO NOT EDIT.

package server

import (
	"context"

	"github.com/grpc-ecosystem/grpc-gateway/runtime"
	"google.golang.org/grpc"

	ery_pb "github.com/srvc/glx/api/ery"
)

// RegisterWithServer implements grapiserver.Server.RegisterWithServer.
func (s *appServiceServerImpl) RegisterWithServer(grpcSvr *grpc.Server) {
	ery_pb.RegisterAppServiceServer(grpcSvr, s)
}

// RegisterWithHandler implements grapiserver.Server.RegisterWithHandler.
func (s *appServiceServerImpl) RegisterWithHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	return ery_pb.RegisterAppServiceHandler(ctx, mux, conn)
}
